project:
  type: website
  output-dir: docs

website:
  title: "Making Sense of the Census"
  navbar:
    left:
      - href: index.qmd
        text: Resources
      - href: making-sense-census-presentation.qmd
        text: Presentation
      

format:
  html:
    theme: cosmo 
    css: styles.css
    toc: true



